---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Lensed"
keywords:    "lensed, lensing, gravitational lensing, reconstruction, fits, mcmc, observations, models, astronomy"
description: "Reconstruct gravitational lenses and lensed sources from strong lensing observations."
source_link: "https://github.com/glenco/lensed"
favicon:     #put a path like: "img/favicon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#000000'
  white:     '#ffffff'
  yellow:    '#b58900'
  orange:    '#cb4b16'
  red:       '#dc322f'
  magenta:   '#d33682'
  violet:    '#6c71c4'
  blue:      '#268bd2'
  cyan:      '#2aa198'
  green:     '#859900'

kramdown:
  auto_ids:  false

