site_name:   Lensed Documentation
site_url:    https://glenco.github.io/lensed/
site_author: The Lensed team

site_description: >
  Reconstruct gravitational lenses and lensed sources from
  strong lensing observations.

repo_url: https://github.com/glenco/lensed

pages:
- 'Documentation':              'index.md'
- 'Getting started':
  - 'Get Lensed':               'releases.md'
  - 'Usage':                    'usage.md'
  - 'Building from source':     'building.md'
  - 'Dependencies':             'dependencies.md'
  - 'Troubleshooting':          'troubleshooting.md'
- 'Running Lensed':
  - 'Configuration files':      'configuration.md'
  - 'Units':                    'units.md'
  - 'Analysing the results':    'results.md'
  - 'Modelling strategies':     'strategies.md'
  - 'Performance & tuning':     'performance.md'
- 'Objects':
  - 'Lenses':                   'lenses.md'
  - 'Sources':                  'sources.md'
  - 'Foregrounds':              'foregrounds.md'
  - 'Creating objects':         'create.md'

theme: readthedocs

extra_css:
- '//cdnjs.cloudflare.com/ajax/libs/KaTeX/0.3.0/katex.min.css'
- 'lensed.css'

extra_javascript:
- '//cdnjs.cloudflare.com/ajax/libs/KaTeX/0.3.0/katex.min.js'
- '//cdnjs.cloudflare.com/ajax/libs/KaTeX/0.3.0/contrib/auto-render.min.js'
- 'lensed.js'

markdown_extensions:
- toc
- footnotes
- fenced_code
- codehilite:
    guess_lang: False
