site_name:   lensed Documentation
site_url:    https://glenco.github.io/lensed
site_author: The lensed team

site_description: >
    Reconstruct gravitational lenses and lensed sources from
    strong lensing observations.

repo_url: https://github.com/GLENCO/lensed

pages:
    - [ 'index.md', 'Documentation', 'Getting started']
    - [ 'coordinates.md', 'Documentation', 'Coordinates']
    - [ 'lenses.md', 'Objects', 'Lenses' ]
    - [ 'sources.md', 'Objects', 'Sources' ]
    - [ 'foregrounds.md', 'Objects', 'Foregrounds' ]

theme: readthedocs

include_search: true

extra_css:
    - '//cdnjs.cloudflare.com/ajax/libs/KaTeX/0.1.1/katex.min.css'
    - 'css/lensed.css'

extra_javascript:
    - '//cdnjs.cloudflare.com/ajax/libs/KaTeX/0.1.1/katex.min.js'
    - 'js/lensed.js'

markdown_extensions:
    - footnotes
    - fenced_code
    - katex
