site_name:   Lensed Documentation
site_url:    https://glenco.github.io/lensed/
site_author: The Lensed team

site_description: >
    Reconstruct gravitational lenses and lensed sources from
    strong lensing observations.

repo_url: https://github.com/glenco/lensed

pages:
    - [ 'index.md',             'Documentation'                             ]
    - [ 'download.md',          'Getting started',  'Get Lensed'            ]
    - [ 'dependencies.md',      'Getting started',  'Dependencies'          ]
    - [ 'building.md',          'Getting started',  'Building'              ]
    - [ 'troubleshooting.md',   'Getting started',  'Troubleshooting'       ]
    - [ 'usage.md',             'Running Lensed',   'Usage'                 ]
    - [ 'configuration.md',     'Running Lensed',   'Configuration files'   ]
    - [ 'units.md',             'Running Lensed',   'Units'                 ]
    - [ 'results.md',           'Running Lensed',   'Results'               ]
    - [ 'strategies.md',        'Running Lensed',   'Modelling strategies'  ]
    - [ 'performance.md',       'Running Lensed',   'Performance'           ]
    - [ 'lenses.md',            'Objects',          'Lenses'                ]
    - [ 'sources.md',           'Objects',          'Sources'               ]
    - [ 'foregrounds.md',       'Objects',          'Foregrounds'           ]
    - [ 'create.md',            'Objects',          'Creating objects'      ]

theme: readthedocs

extra_css:
    - '//cdnjs.cloudflare.com/ajax/libs/KaTeX/0.3.0/katex.min.css'
    - 'lensed.css'

extra_javascript:
    - '//cdnjs.cloudflare.com/ajax/libs/KaTeX/0.3.0/katex.min.js'
    - '//cdnjs.cloudflare.com/ajax/libs/KaTeX/0.3.0/contrib/auto-render.min.js'
    - 'lensed.js'

markdown_extensions:
    - toc
    - footnotes
    - fenced_code
